name = "Iris Shaders"
filename = "iris-mc1.19.4-1.6.3.jar"
version = "1.6.3+1.19.4"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/AQqB1OqQ/iris-mc1.19.4-1.6.3.jar"
hash_format = "sha1"
hash = "58fab3e31c03d9830ee614deadb705e54491b8b6"
