name = "Sodium"
filename = "sodium-fabric-mc1.19.4-0.4.10+build.24.jar"
version = "mc1.19.4-0.4.10"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/AANobbMI/versions/b4hTi3mo/sodium-fabric-mc1.19.4-0.4.10%2Bbuild.24.jar"
hash_format = "sha1"
hash = "b060680929d7a6d130fb980a9f9907461df05fa1"
